#!/usr/bin/env bash
# =============================================================================
# Matrix Server — post-install system tuning
# =============================================================================
# Применяет рекомендуемые системные настройки для Matrix + Element X workload:
#   - sysctl: BBR, TCP keepalive для long-poll, tcp_notsent_lowat (low-latency)
#   - nginx: worker_rlimit, keepalive_timeout, http2 streams, ssl_buffer
#   - systemd: LimitNOFILE drop-in для nginx
#
# Запуск (от root):
#   bash tune-system.sh [--dry-run]
#
# Идемпотентен. Безопасно перезапускать.
# =============================================================================

set -euo pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

run() {
    if $DRY_RUN; then printf '[dry-run] %s\n' "$*"; else "$@"; fi
}

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*" >&2; }

[[ "$EUID" -eq 0 ]] || { warn "Запуск от root"; exit 1; }

# =============================================================================
# 1) sysctl — TCP для long-poll + mobile lossy networks
# =============================================================================
log "sysctl: BBR + keepalive 60s + buffers"

# BBR доступен на Linux 4.9+ — проверим, чтобы не упасть на старом ядре
HAS_BBR=0
modprobe tcp_bbr 2>/dev/null || true
if [[ -f /proc/sys/net/ipv4/tcp_available_congestion_control ]] && \
   grep -q bbr /proc/sys/net/ipv4/tcp_available_congestion_control; then
    HAS_BBR=1
fi

SYSCTL_CONF=/etc/sysctl.d/99-matrix-tuning.conf
TUNING="# Matrix homeserver tuning — long-poll + lossy networks
# Generated by tune-system.sh

# TCP keepalive — критично для /sync long-poll через NAT/proxy.
# Default 7200s = 2 часа: idle connection silently дропается в NAT.
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6

# Backlog
net.ipv4.tcp_max_syn_backlog = 2048
net.core.netdev_max_backlog = 4096
net.core.somaxconn = 4096

# Port range + fin timeout
net.ipv4.ip_local_port_range = 10000 65535
net.ipv4.tcp_fin_timeout = 30

# Buffers (16MB max) — long-running sync streams
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# Latency / mobile-friendly
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_fastopen = 3"

if [[ "$HAS_BBR" -eq 1 ]]; then
    TUNING+="

# BBR congestion control — значительно лучше cubic на lossy/wireless
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr"
else
    warn "BBR недоступен на этом ядре — пропускаю (Linux 4.9+ нужен)"
fi

if $DRY_RUN; then
    echo "[dry-run] would write $SYSCTL_CONF"
    echo "$TUNING"
else
    echo "$TUNING" > "$SYSCTL_CONF"
    sysctl --system >/dev/null 2>&1 || warn "sysctl --system warned"
fi

log "  current congestion: $(sysctl -n net.ipv4.tcp_congestion_control)"
log "  current keepalive:  $(sysctl -n net.ipv4.tcp_keepalive_time)s"

# =============================================================================
# 2) nginx — worker, keepalive, ssl
# =============================================================================
if [[ -f /etc/nginx/nginx.conf ]]; then
    log "nginx: worker_rlimit + keepalive + ssl_buffer + http2 streams"

    add_if_missing() {
        local key="$1" value="$2" file="$3"
        if ! grep -qE "^\s*${key}\s" "$file"; then
            sed -i "/^http {/a\\    ${key} ${value};" "$file"
            log "  + ${key} ${value}"
        fi
    }

    if ! $DRY_RUN; then
        # worker_rlimit_nofile — глобально, до events{}
        if ! grep -qE "^\s*worker_rlimit_nofile\s" /etc/nginx/nginx.conf; then
            sed -i '/^worker_processes/a worker_rlimit_nofile 32768;' /etc/nginx/nginx.conf
            log "  + worker_rlimit_nofile 32768"
        fi

        # worker_connections в events{}
        if grep -qE "^\s*worker_connections\s+1024" /etc/nginx/nginx.conf; then
            sed -i 's/worker_connections 1024/worker_connections 2048/' /etc/nginx/nginx.conf
            log "  worker_connections 1024 -> 2048"
        fi

        # keepalive_timeout, ssl_buffer и др. — в http{}
        add_if_missing "keepalive_timeout"          "300s"      /etc/nginx/nginx.conf
        add_if_missing "keepalive_requests"         "1000"      /etc/nginx/nginx.conf
        add_if_missing "ssl_buffer_size"            "4k"        /etc/nginx/nginx.conf
        add_if_missing "http2_max_concurrent_streams" "256"     /etc/nginx/nginx.conf
        add_if_missing "send_timeout"               "300s"      /etc/nginx/nginx.conf
        add_if_missing "reset_timedout_connection"  "on"        /etc/nginx/nginx.conf
        add_if_missing "client_header_timeout"      "30s"       /etc/nginx/nginx.conf
        add_if_missing "client_body_timeout"        "60s"       /etc/nginx/nginx.conf
    fi
else
    warn "/etc/nginx/nginx.conf не найден — nginx tuning пропущен"
fi

# =============================================================================
# 3) systemd — LimitNOFILE drop-in для nginx
# =============================================================================
if systemctl list-unit-files nginx.service &>/dev/null; then
    log "systemd: LimitNOFILE=65535 drop-in для nginx"
    if ! $DRY_RUN; then
        mkdir -p /etc/systemd/system/nginx.service.d
        cat > /etc/systemd/system/nginx.service.d/limits.conf <<'EOF'
[Service]
LimitNOFILE=65535
EOF
        systemctl daemon-reload
    fi
fi

# =============================================================================
# 4) Apply nginx config (test + reload)
# =============================================================================
if [[ -f /etc/nginx/nginx.conf ]] && command -v nginx &>/dev/null; then
    if ! $DRY_RUN; then
        if nginx -t 2>&1 | grep -q "test is successful"; then
            systemctl reload nginx 2>/dev/null || nginx -s reload
            log "nginx reloaded"
        else
            warn "nginx -t failed — НЕ перезагружаю. Проверь вручную:"
            nginx -t || true
        fi
    fi
fi

log "Готово. Tuning применён."
log ""
log "Что сделано:"
log "  • sysctl: $SYSCTL_CONF (BBR=$HAS_BBR, tcp_keepalive=60s)"
log "  • nginx: keepalive_timeout 300s, http2_streams 256, worker_rlimit 32768"
log "  • systemd: nginx LimitNOFILE=65535"
log ""
log "Откат: rm $SYSCTL_CONF + sysctl --system + restore /etc/nginx/nginx.conf"
